name: 'Build on Linux'
description: 'Build C++ and Python binaries for testing on Linux'

inputs:
  cmake-args:
    description: 'The args for generating CMake project'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python package
      shell: bash
      env:
        DEBUG: 1
        CMAKE_ARGS: ${{ inputs.cmake-args }}
      run: |
        # Install cpu-only torch to save space
        uv pip install torch --index-url https://download.pytorch.org/whl/cpu
        uv pip install --no-build-isolation -e ".[dev]" -v

    - name: Build CPP only
      shell: bash
      run: |
        cmake . -B build -DCMAKE_BUILD_TYPE=Debug ${{ inputs.cmake-args }}
        cmake --build build -j $(nproc)
