name: 'Build on Windows'
description: 'Build C++ and Python binaries for testing on Windows'

inputs:
  cmake-args:
    description: 'The args for generating CMake project'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python package
      shell: cmd
      env:
        CMAKE_ARGS: ${{ inputs.cmake-args }}
      run: uv pip install ".[dev]" -v

    - name: Build CPP only
      shell: cmd
      run: |
        cmake . -B build ${{ inputs.cmake-args }}
        cmake --build build -j %NUMBER_OF_PROCESSORS%
